ci: release workflow
timofurrer/retry-cmd pull request #2
Opened 2023-03-23 21:21 UTC by trim21

2023-03-24 08:07 UTC, timofurrer requested changes
@trim21 already looks pretty solid. 

I've left a few comments and back to you 🏓

2023-03-24 08:07 UTC, timofurrer commented on .github/workflows/build.yaml
> +      - uses: brndnmtthws/rust-action-rustup@v1
What's the reason for using this and not `actions-rs/toolchain@v1` ?

2023-03-24 08:07 UTC, timofurrer commented on .github/workflows/build.yaml
> +      - uses: Swatinem/rust-cache@v2
It's not a huge project and won't be built often, so I'd rather only rely on what is really necessary:

```suggestion

```

2023-03-24 08:07 UTC, timofurrer commented on .github/workflows/build.yaml
> +
I think we don't really care about the directory, so `target` is good enough?

```suggestion
```

2023-03-24 08:07 UTC, timofurrer commented on .github/workflows/build.yaml
> +          path: dist/release/retry
Goes with the above suggestion to leave it at `target`:

```suggestion
          path: target/release/retry

```

2023-03-24 08:07 UTC, timofurrer commented on .github/workflows/release.yaml
> +  release:
Please apply the same suggestions as the ones I left for the `build` workflow.

2023-03-24 08:41 UTC, trim21 commented on .github/workflows/build.yaml
> +      - uses: brndnmtthws/rust-action-rustup@v1
it hasn't update since 2020 and still using deprecsted `set-output` command

2023-04-02 07:41 UTC, merged

2023-04-02 07:41 UTC, timofurrer commented
LGTM! Thanks @trim21 !

2023-04-02 07:45 UTC, trim21 commented
new tag please?

2023-04-03 10:17 UTC, timofurrer commented
@trim21 there is a [v1.0.1](https://github.com/timofurrer/retry-cmd/releases/tag/v1.0.1) release now!